# This program is to examine the heating generated by LRF
# %% section 1: Load modules
import numpy as np
import joblib as jl
import matplotlib.pyplot as plt

# %% section 2: Load data
## 1. LRF heating
lrf_name: str = "/home/b11209013/2024_Research/MPAS/LRF_heating/heating_file/CNTL_heating.joblib"

lrf_data = jl.load(lrf_name)

dims = {
    'lat': lrf_data['lat'],
    'lon': lrf_data['lon']
}

## 2. MPAS heating
mpas_name: str = "/work/b11209013/2024_Research/MPAS/PC/CNTL_PC.joblib"

mpas_data = jl.load(mpas_name)

data = {
    'pc1': {
        'lw': {
            'lrf': lrf_data['pc1']['lw'].mean(axis=0),
            'mpas': mpas_data['pc']['lw'][0].mean(axis=0)
        },
        'sw': {
            'lrf': lrf_data['pc1']['sw'].mean(axis=0),
            'mpas': mpas_data['pc']['sw'][0].mean(axis=0)
        },
        'cu': {
            'lrf': lrf_data['pc1']['cu'].mean(axis=0),
            'mpas': mpas_data['pc']['cu'][0].mean(axis=0)
        },
    },
    'pc2': {
        'lw': {
            'lrf': lrf_data['pc2']['lw'].mean(axis=0),
            'mpas': mpas_data['pc']['lw'][1].mean(axis=0)
        },
        'sw': {
            'lrf': lrf_data['pc2']['sw'].mean(axis=0),
            'mpas': mpas_data['pc']['sw'][1].mean(axis=0)
        },
        'cu': {
            'lrf': lrf_data['pc2']['cu'].mean(axis=0),
            'mpas': mpas_data['pc']['cu'][1].mean(axis=0)
        },
    }
}

# %% section 3: plot
plt.contourf(dims['lon'], dims['lat'], data['pc1']['lw']['lrf'], cmap='coolwarm')
plt.title('LRF PC1 LW')
plt.colorbar()
plt.show()
plt.contourf(dims['lon'], dims['lat'], data['pc1']['lw']['mpas'], cmap='coolwarm')
plt.title('MPAS PC1 LW')
plt.colorbar()
plt.show()
# %%
